### ISSUE TITLE
Symlink from /sbin to /usr/sbin is destroyed by pkginst

### ISSUE THREAD

**Issue by michaelpennington** [pghvlaans/yalpack#1]
This is a great project, but in order to be forwards compatible with newer versions of LFS (development version after 10.1) it should preserve the symlink between /sbin and /usr/sbin. Thank you for your great work and I look forward to using it in the future!

**Comment by pghvlaans** [comment]
Hi, Michael. Thanks for reaching out.

I'll look into this. ~~If you don't mind my asking, which package was being installed, and what version of yalpack do you have?~~ Issue reproduced. Thanks!

**Comment by pghvlaans** [comment]
It seems like the actual pkginst fix is easy enough, but some of the other scripts will need more extensive editing (especially pkgremove). I'll make this the top-priority fix before the next LFS release.

**Comment by michaelpennington** [comment]
Great, thank you so much!

**Comment by pghvlaans** [comment]
Status: The issue appears to be fixed. yalpack-0.1.5 will be released once full build tests have been completed for 10.1 and 10.1+, along with other testing. The issue will be closed when the new yalpack release is posted (hopefully sometime on the 21st or 22nd, GMT).

**Comment by pghvlaans** [comment]
The release is up, so I'll go ahead and close the issue. Among other improvements, installations under /sbin, /bin, etc. no longer remove symlinks in the development version. Thanks again for bringing this to my attention.
